### ISSUE TITLE
Dart pub

### ISSUE THREAD

**Issue by RusKryzhanovskiy** [thyagoluciano/sm2#2]
Hello, you wrote a great package, and as I understand it, this is your package pub.dev/packages/sm2 
Can you set the correct links in pub.dev? Because at the moment the buttons “Repository (GitHub)” and “View/report problems” refer to github.com/thyagoluciano/flutter_radio

**Comment by thyagoluciano** [comment]
Hello, thanks for feedback, sorry for the links, I fixed it and published a new version.
